In [34]:
#Plan: 
# Find out which words have the biggest impact on price movement (playing around with min_df)
# Once we have a set amount of words, use a sentiment analysis on that subset + look at the distribution
# of those words over time
# Read through Calvin's notes again and be able to properly explain the eighen vectors involved and what
# The new components actually mean for my models. Use prior notes AND ppt/github
# Look into 'stemming' - Calvin

In [16]:
import pandas as pd
import re
import datetime as dt
from datetime import datetime
from datetime import timedelta
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import matplotlib as plot
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.naive_bayes import MultinomialNB, BernoulliNB, GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [3]:
# Count vectorize on words #

In [4]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
stop += ['http', 'https', 'realdonaldtrump', 'co', 'amp']

In [5]:
#remove adjectives/verbs and keep economic terms/countries/names

In [8]:
df_final = pd.read_csv('lsa.csv')

In [9]:
df_final.head()

,Unnamed: 0,pct_sig_ch_high_low,hour_1,hour_2,hour_3,hour_4,hour_5,hour_6,hour_7,hour_8,...,china,cruz,ted,crowd,spend,vader_compound,vader_neg,vader_neu,vader_pos,sig_ch_abs
0,2016-01-03 23:18:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,-0.6249,0.227,0.773,0.000,0
1,2016-01-03 23:19:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,-0.5267,0.159,0.841,0.000,0
2,2016-01-04 00:26:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.9184,0.000,0.500,0.500,0
3,2016-01-04 11:42:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0.5719,0.000,0.844,0.156,0
4,2016-01-04 17:31:00+00:00,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0.5562,0.000,0.834,0.166,0

In [10]:
df_final.index = df_final['Unnamed: 0']

In [ ]:
sparsed_words = []
for i in range(0, sp500_trump_df.shape[0]):
    sparsed_words.append(sp500_trump_df.text.iloc[i])

In [ ]:
en_nlp = textacy.load_spacy('en_core_web_sm')

In [ ]:
parsed =en_nlp(sparsed_words)

In [ ]:
X = sp500_trump_df.text
y = sp500_trump_df['pct_ch_sig']
tfidf = TfidfVectorizer(ngram_range=(1,3), stop_words=stop, max_df=50)
X_tfidf = tfidf.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=.2, random_state=42)

In [16]:
X = sp500_trump_df.text
y = sp500_trump_df['pct_ch_sig']
tfidf = TfidfVectorizer(ngram_range=(1,3), stop_words=stop, max_df=50)
X_tfidf = tfidf.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=.2, random_state=42)

In [ ]:
# Look into tfidf #

In [20]:
X_train

<6056x130824 sparse matrix of type '<class 'numpy.float64'>'
	with 143686 stored elements in Compressed Sparse Row format>

In [21]:
X_freq = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names())

In [25]:
X_freq

,00 00,00 00 enjoy,00 afghanistan,00 afghanistan iraq,00 afternoon,00 afternoon see,00 bedminster,00 big,00 big wins,00 clock,...,چهل_سال_شکست شده,چهل_سال_شکست شده است,که,که مدتهاست,که مدتهاست در,۴۰,۴۰ سال,۴۰ سال ترور,۴۰ سال سرکوب,۴۰ سال فساد
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7541,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7542,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7543,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7544,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7545,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7546,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7547,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7548,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7549,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7550,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7551,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7552,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7553,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7554,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7555,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7556,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7557,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7558,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7559,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7560,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7561,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7562,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7563,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7564,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7565,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7566,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7568,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7569,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7570,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
freq

jobs jobs       9.045996
imwithyou       8.915593
votetrump       8.329408
live            7.812613
texas           7.768041
                  ...
سال فساد ۴۰     0.107833
سال فساد        0.107833
سال سرکوب ۴۰    0.107833
سال سرکوب       0.107833
۴۰ سال فساد     0.107833
Length: 130824, dtype: float64

In [ ]:
#non-vowells to omit

In [53]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(6056, 129156)
(6056,)
(1515, 129156)
(1515,)

In [17]:
from sklearn.model_selection import GridSearchCV, StratifiedShuffleSplit, train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeRegressor

In [27]:
param_dict = {}
model_dict = {
    'lr':GridSearchCV(LogisticRegression(),
                      param_grid=param_dict,verbose=1
                      ),
    'rf':GridSearchCV(RandomForestClassifier(),
                      param_grid=param_dict,verbose=1
                      ),
    'knn':GridSearchCV(KNeighborsClassifier(),
                      param_grid=param_dict,verbose=1
                      ),
    'mnb':GridSearchCV(MultinomialNB(),
                    param_grid=param_dict,verbose=1
                             )
}

In [28]:
baseline = sp500_trump_df.pct_ch_sig.value_counts(normalize=True).max()
baseline

0.49372605996565844

In [29]:
## Tune the models (l1) ##

In [30]:
LogisticRegression()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [35]:
param_dict = {
    'mnb':{
        'alpha': np.linspace(.1,1,5)},
    'lr':{
        'C': np.logspace(-3,3,7), 'solver' : ['newton-cg', 'lbfgs', 'saga'],\
        'penalty': ['l2'], 'multi_class': ['multinomial', 'ovr'], 'max_iter': [20000,40000]},
    'rf':{
        'max_depth': [5,10,20,30,40],
        'min_samples_leaf': [1,2,5,8],
        'criterion': ['gini','entropy'],
        'n_estimators': [5,10,15]},
    'knn':{
        'n_neighbors': np.arange(5,50,3)}

}

In [36]:
model_dict = {
    'lr':GridSearchCV(LogisticRegression(),
                      param_grid=param_dict['lr'],
                      cv=StratifiedShuffleSplit(n_splits=5, random_state=42)),
    'rf':GridSearchCV(RandomForestClassifier(),
                      param_grid=param_dict['rf'],
                      cv=StratifiedShuffleSplit(n_splits=5, random_state=42)),
    'knn':GridSearchCV(KNeighborsClassifier(),
                      param_grid=param_dict['knn'],
                      cv=StratifiedShuffleSplit(n_splits=5, random_state=42)),
    'mnb':GridSearchCV(MultinomialNB(),
                             param_grid=param_dict['mnb'],
                             cv=StratifiedShuffleSplit(n_splits=5, random_state=42))
}


# Add SVM from Monday

In [37]:
sp500_trump_df.shape[0]

7571

In [38]:
from tqdm import tqdm_notebook

In [39]:
def fit_all_models(X_train_std,y_train,X_test_std, y_test, model_dict):
    for model in model_dict.keys():
        model_dict[model].fit(X_train,y_train)
        print("{} model best score: {}".format(model, model_dict[model].best_score_)) # returns the cross-val mean of the best model
        print("{} model best params: {}".format(model, model_dict[model].best_params_))
        print("{} model best predictions: {}".format(model, model_dict[model].predict(X_test)))
        print("{} model test score: {}".format(model, model_dict[model].score(X_test_std, y_test)))

In [66]:
start = datetime.now()

fit_all_models(X_train, y_train, X_test, y_test, model_dict)

end = datetime.now()
print(end - start)

lr model best score: 0.49504950495049505
lr model best params: {'C': 0.001, 'max_iter': 20000, 'multi_class': 'multinomial', 'penalty': 'l2', 'solver': 'newton-cg'}
lr model best predictions: [0 0 0 ... 0 0 0]
lr model test score: 0.4871287128712871
rf model best score: 0.49636963696369635
rf model best params: {'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 1, 'n_estimators': 5}
rf model best predictions: [0 0 0 ... 0 0 0]
rf model test score: 0.4864686468646865
knn model best score: 0.4891089108910891
knn model best params: {'n_neighbors': 44}
knn model best predictions: [ 0  0  0 ... -1  0  0]
knn model test score: 0.4778877887788779
mnb model best score: 0.49504950495049505
mnb model best params: {'alpha': 1.0}
mnb model best predictions: [0 0 0 ... 0 0 0]
mnb model test score: 0.4871287128712871
0:36:34.536612

In [51]:
logreg = LogisticRegression(C= 0.001, max_iter= 20000,
                            multi_class= 'multinomial',
                            penalty = 'l2',
                            solver= 'newton-cg')

In [52]:
logreg.fit(X_train, y_train)

LogisticRegression(C=0.001, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=20000,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)

In [53]:
logreg.score(X_test,y_test)

0.4871287128712871

In [59]:
logreg.coef_.max()

0.0014819144032640651

In [34]:
## Each word has a coefficiant?? Use it to determine which has the biggest impact

In [67]:
sp500_trump_df.shape

(7571, 65)

In [68]:
len(sp500_trump_df.text.iloc[0])

82

In [69]:
sp500_trump_df['tweet_length'] = [len(word.split()) for word in sp500_trump_df['text']]

In [70]:
sp500_trump_df.shape

(7571, 66)

In [ ]:
## Sentiment Analysis ##

In [ ]:
# Using tfidf which is measuring the occurance and frequency of words within each tweet
# Within this model, the rarer words are contributing more weight to the model.
# If the words are contained in a significant amount of tweets, they bare less 
# weight for the model
# Truncated SVD is adopted because of the size of the tfidf matrix for each
# word contained in Trump's 7571 tweets
# SVD will find the most valuable terms and

In [13]:
import textacy
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from tqdm import tqdm_notebook

/Users/harryfield/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)

In [14]:
from sklearn.decomposition import TruncatedSVD

In [24]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer

In [26]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
stop += ['http', 'https', 'realdonaldtrump', 'co', 'people', 'trump', 'thank', 'new'\
         'today', 'amp', 'president', 'new', 'today', 'last', 'night', 'right', 'let'\
        'highly']

In [27]:
tfidf = TfidfVectorizer(ngram_range=(1,3), stop_words=stop, max_df=50)

In [33]:
df_final.columns

Index(['Unnamed: 0', 'pct_sig_ch_high_low', 'hour_1', 'hour_2', 'hour_3',
       'hour_4', 'hour_5', 'hour_6', 'hour_7', 'hour_8', 'hour_9', 'hour_10',
       'hour_11', 'hour_12', 'hour_13', 'hour_14', 'hour_15', 'hour_16',
       'hour_17', 'hour_18', 'hour_19', 'hour_20', 'hour_21', 'hour_22',
       'hour_23', 'vol_20_avg', 'sustained_vol', 'processed_title',
       'tokenised_title', 'stemmed_titles', 'lemmed_titles', 'text_lower',
       'index_x', 'text_y', 'pct_ch', 'NORP', 'ORG', 'PERCENT', 'PERSON',
       'CCONJ', 'INTJ', 'PUNCT', 'LOC', 'PRODUCT', 'WORK_OF_ART', 'AUX',
       'Sentiment_Polarity', 'index_y', 'discussion', 'fitn', 'jeb', 'bush',
       'missile', 'hampshire', 'respected', 'iowa', 'oil', 'graham', 'marine',
       'waste', 'tariff', 'inform', 'syria', 'votetrump', 'canada',
       'congressman', 'east', 'disgrace', 'little', 'safety', 'problem', 'buy',
       'china', 'cruz', 'ted', 'crowd', 'spend', 'vader_compound', 'vader_neg',
       'vader_neu', 'vader_pos', 'sig_ch_abs'],
      dtype='object')

In [50]:
df_subset = df_final[df_final.sig_ch_abs==1]

In [51]:
df_subset.shape

(526, 82)

In [52]:
X = df_subset.text_lower
y = df_subset['sig_ch_abs']
tfidf = TfidfVectorizer(ngram_range=(1,3), stop_words=stop, max_df=50)
X_tfidf = tfidf.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=.2, random_state=42)

In [53]:
def perform_latent_semantic_analysis(n_components, vectorizer):
    SVD = TruncatedSVD(n_components)
    component_names = ["component_"+str(i+1) for i in range(n_components)] #components being used to categorise tweets & words
    latent_semantic_analysis = pd.DataFrame(SVD.fit_transform(X_tfidf),
                                            index = df_subset['text_lower'].index,
                                            columns = component_names)
    vocabulary_expression = pd.DataFrame(SVD.components_,
                                         index = component_names,
                                         columns = vectorizer.get_feature_names())
    eigen_vector = SVD.singular_values_
                                
    svd = SVD
    return latent_semantic_analysis, vocabulary_expression, svd, eigen_vector

In [54]:
latent_semantic_analysis, vocabulary_expression, svd, eigen_vector = perform_latent_semantic_analysis(10, tfidf)

In [83]:
eigen_vector

array([2.337229  , 2.18018878, 2.07953726, 1.79386389, 1.61144732,
       1.55664703, 1.51822067, 1.48735235, 1.42803064, 1.41359083])

In [84]:
latent_semantic_analysis['text'] = sp500_trump_df['text']
latent_semantic_analysis['class'] = sp500_trump_df['pct_ch_sig']

In [55]:
svd.explained_variance_.cumsum()*100

array([0.42968572, 0.8020944 , 1.0311891 , 1.36626645, 1.66199142,
       1.96742093, 2.26594225, 2.55554885, 2.84060266, 3.11963973])

In [ ]:
# Key rare words with a reasonable amount of rarity

In [ ]:
# Sentiment analysis based on tweets with those words

In [86]:
X_tfidf.shape

(7571, 129156)

In [87]:
X_svd = svd.fit_transform(X_tfidf)

In [88]:
X_svd.shape

(7571, 10)

In [89]:
# The reduction of 3462 to just 5 is categorising words based on their probability to appear in the same tweet

In [90]:
latent_semantic_analysis.head(10)

,component_1,component_2,component_3,component_4,component_5,component_6,component_7,component_8,component_9,component_10,text,class
Unnamed: 0,,,,,,,,,,,,
2016-01-03 23:18:00+00:00,0.000017,0.000004,0.000052,0.001794,-0.001213,-0.002832,-0.006358,-0.005393,0.004969,-0.003451,The worst thing Hillary could do is have her h...,-1
2016-01-03 23:19:00+00:00,-0.000025,0.000027,0.000083,-0.000007,0.000885,-0.003745,-0.000784,0.002884,0.000341,-0.002108,"By the way, Hillary &amp; the MSM forgot to me...",-1
2016-01-04 00:26:00+00:00,-0.000134,0.000045,-0.000301,0.000031,-0.002619,-0.000304,-0.002187,0.003731,-0.008887,-0.004173,"""@icareeguns: This #Iowan is voting for @RealD...",-1
2016-01-04 11:42:00+00:00,-0.000022,-0.000029,0.000155,-0.000242,0.000343,0.000196,-0.000579,0.003596,-0.000434,-0.001215,"""@RhettRiley1234: Trump only wins with our vot...",1
2016-01-04 17:31:00+00:00,-0.000029,-0.000011,0.000415,0.000769,-0.004936,-0.002992,-0.008340,0.007162,-0.002410,-0.002538,"I look forward to being in Lowell, Massachuset...",-1
2016-01-04 20:00:00+00:00,-0.000023,-0.000117,0.000030,0.000067,0.002103,-0.002934,0.007065,0.002167,-0.002820,0.006081,"Woody Johnson, owner of the NYJets, is @JebBus...",1
2016-01-05 02:20:00+00:00,0.000072,-0.000033,0.000582,0.000243,-0.000806,-0.000018,-0.000785,0.001825,-0.002400,-0.022626,"The rally in Lowell, Massachusetts, was amazin...",-1
2016-01-05 02:22:00+00:00,0.000082,0.000148,0.000456,-0.001996,-0.000836,0.003365,0.004405,0.007660,-0.002429,-0.003430,"""@troyconway: Now 2-more IT Firms going over s...",1
2016-01-05 02:28:00+00:00,0.000014,-0.000036,0.000011,0.000602,0.000536,0.000131,0.001292,-0.001138,-0.003038,-0.002934,"""@thecybermenace: @realDonaldTrump Donald Trum...",1
2016-01-05 03:33:00+00:00,-0.000066,-0.000053,0.000007,-0.000058,0.003085,-0.001976,0.003181,-0.001132,-0.005307,0.006849,"""@samuelghaddad: Wow! Let's hear it for the Fa...",-1

In [91]:
latent_semantic_analysis.sample(10)

,component_1,component_2,component_3,component_4,component_5,component_6,component_7,component_8,component_9,component_10,text,class
Unnamed: 0,,,,,,,,,,,,
2019-07-30 19:58:00+00:00,-0.000007,6.140785e-07,0.000009,0.000548,0.000020,-0.001049,-0.001390,0.001147,-0.000146,0.001225,https://t.co/sPd4GF6wxu,0
2017-07-24 10:52:00+00:00,-0.000020,4.315131e-05,-0.000006,-0.001562,0.003634,-0.003736,0.005582,0.003164,0.004408,-0.002795,After 1 year of investigation with Zero eviden...,1
2017-11-09 23:44:00+00:00,-0.000098,1.149107e-04,-0.000470,0.000508,-0.010221,0.006854,0.004437,0.015586,0.008292,0.014526,My meetings with President Xi Jinping were ver...,-1
2018-03-27 00:44:00+00:00,-0.000086,-6.256492e-05,-0.000154,-0.000028,-0.002456,-0.000418,-0.000201,0.002214,-0.003517,0.000199,Trade talks going on with numerous countries t...,-1
2016-08-12 10:26:00+00:00,-0.000076,-1.013630e-04,0.000222,0.000295,-0.005058,-0.004312,0.001767,0.006612,0.002598,-0.001211,Ratings challenged @CNN reports so seriously t...,-1
2017-02-15 16:34:00+00:00,-0.000107,7.048360e-05,-0.000061,-0.000726,-0.003167,-0.000926,0.004589,0.006507,-0.001131,0.010356,Great listening session with CEO's of the Reta...,1
2016-05-24 02:38:00+00:00,-0.000075,-2.498728e-06,-0.000070,-0.000305,-0.003119,-0.003534,-0.003174,0.000452,-0.000778,0.004587,"While under no obligation to do so, I have rai...",1
2016-12-21 13:24:00+00:00,-0.000099,-1.434980e-05,-0.000231,-0.000989,0.004899,0.002071,0.000736,-0.006121,0.000615,0.001358,"I would have done even better in the election,...",1
2016-10-10 01:28:00+00:00,-0.000042,1.130899e-04,-0.000116,0.000637,-0.000311,0.000832,-0.000261,-0.003476,0.003941,-0.000785,Basically nothing Hillary has said about her s...,1
2016-01-05 02:22:00+00:00,0.000082,1.480457e-04,0.000456,-0.001996,-0.000836,0.003365,0.004405,0.007660,-0.002429,-0.003430,"""@troyconway: Now 2-more IT Firms going over s...",1

In [92]:
latent_semantic_analysis.var()

component_1     0.000721
component_2     0.000627
component_3     0.000571
component_4     0.000424
component_5     0.000342
component_6     0.000320
component_7     0.000304
component_8     0.000292
component_9     0.000269
component_10    0.000263
class           0.506276
dtype: float64

In [65]:
vocabulary_expression.abs().T.sort_values('component_10', ascending=False).head(10)

,component_1,component_2,component_3,component_4,component_5,component_6,component_7,component_8,component_9,component_10
china,0.035320,0.048382,0.113031,0.199983,0.100704,0.011765,0.028308,0.049661,0.129343,0.221605
witch,0.001676,0.019302,0.003674,0.046561,0.068783,0.123620,0.152480,0.170329,0.087290,0.161541
witch hunt,0.001676,0.019302,0.003674,0.046561,0.068783,0.123620,0.152480,0.170329,0.087290,0.161541
hunt,0.001676,0.019302,0.003674,0.046561,0.068783,0.123620,0.152480,0.170329,0.087290,0.161541
immigration,0.019246,0.015444,0.091873,0.012000,0.107077,0.016862,0.018674,0.060950,0.085905,0.082042
deal,0.025718,0.006560,0.053528,0.038191,0.007882,0.021261,0.009643,0.018781,0.095671,0.080778
job,0.005665,0.012478,0.050109,0.033427,0.039611,0.025634,0.077825,0.110999,0.084776,0.075963
country,0.015028,0.027277,0.122536,0.073967,0.015073,0.007822,0.014130,0.004827,0.058149,0.073315
great job,0.004940,0.008546,0.034486,0.023256,0.023411,0.024462,0.062491,0.096717,0.072841,0.071166
cruz,0.021388,0.047618,0.164676,0.197954,0.113619,0.063376,0.075437,0.031146,0.000257,0.069480

In [95]:
vocabulary_expression.abs().T.sort_values('component_5', ascending=False).head(20)

,component_1,component_2,component_3,component_4,component_5,component_6,component_7,component_8,component_9,component_10
interviewed oreillyfactor,0.000339,0.001111,0.000763,0.055551,0.397193,0.049946,0.009379,0.001038,0.011261,0.020000
oreillyfactor tonight,0.000373,0.001193,0.000737,0.052715,0.386701,0.042013,0.015458,0.000147,0.008156,0.005817
interviewed oreillyfactor tonight,0.000353,0.001066,0.000590,0.050211,0.358203,0.038190,0.010829,0.000878,0.008738,0.003511
tonight 00,0.000192,0.000536,0.000336,0.039337,0.290725,0.023479,0.003307,0.022095,0.013222,0.006406
oreillyfactor tonight 00,0.000165,0.000549,0.000230,0.030236,0.202848,0.020261,0.002857,0.003536,0.005902,0.006012
eastern,0.000113,0.000366,0.000504,0.073288,0.155243,0.014560,0.005475,0.006745,0.012258,0.049976
tonight 00 enjoy,0.000092,0.000415,0.000017,0.017998,0.145690,0.014532,0.000414,0.008724,0.009592,0.001396
00 eastern,0.000076,0.000172,0.000236,0.029363,0.145604,0.012547,0.003046,0.007107,0.013443,0.045900
tonight 00 eastern,0.000050,0.000153,0.000077,0.022814,0.126801,0.012111,0.001258,0.003742,0.006629,0.022576
eastern enjoy,0.000015,0.000025,0.000242,0.066811,0.099652,0.010936,0.002330,0.001648,0.001759,0.012123
00 eastern enjoy,0.000059,0.000183,0.000056,0.015941,0.090441,0.008898,0.000560,0.001389,0.003067,0.007802
jobsnotmobs,0.000540,0.001149,0.002021,0.009804,0.087600,0.032321,0.061959,0.019342,0.113599,0.098167
tonight foxnews,0.000182,0.000058,0.000350,0.009703,0.077626,0.013119,0.006613,0.003469,0.007993,0.023603
oreillyfactor tonight florida,0.000084,0.000274,0.000186,0.009858,0.075357,0.008374,0.003474,0.000742,0.001334,0.003308
florida enjoy,0.000084,0.000274,0.000186,0.009858,0.075357,0.008374,0.003474,0.000742,0.001334,0.003308
tonight florida,0.000084,0.000274,0.000186,0.009858,0.075357,0.008374,0.003474,0.000742,0.001334,0.003308
tonight florida enjoy,0.000084,0.000274,0.000186,0.009858,0.075357,0.008374,0.003474,0.000742,0.001334,0.003308
oreillyfactor 00,0.000073,0.000010,0.000392,0.010521,0.074930,0.028517,0.005123,0.000860,0.006383,0.043384
oreillyfactor 00 enjoy,0.000073,0.000010,0.000392,0.010521,0.074930,0.028517,0.005123,0.000860,0.006383,0.043384
oreillyfactor tonight foxnews,0.000091,0.000143,0.000074,0.008928,0.069928,0.008877,0.004113,0.001922,0.002324,0.006277

NameError: name 'sp500_trump' is not defined

In [96]:
svd_5 = svd

In [97]:
def svd_variance(svd_model, col_index):
    
    dimensions = ['Dimension {}'.format(i) for i in range(1,len(svd_model.components_)+1)]
    components = pd.DataFrame(np.round(svd_model.components_, 4), columns=col_index)
    ratios = svd_model.explained_variance_ratio_.reshape(len(svd_model.components_), 1)
    variance_ratios = pd.DataFrame(np.round(ratios, 4), columns = ['Explained Variance'])
    variance_ratios.index = dimensions

    fig, ax = plt.subplots(figsize = (24,10))

    # Plot the feature weights as a function of the components
    components.plot(ax = ax, kind = 'bar',legend='False');
    ax.set_ylabel("Feature Weights")
    ax.set_xticklabels(dimensions, rotation=0)
    ax.legend_.remove()


    # Display the explained variance ratios
    for i, ev in enumerate(svd_model.explained_variance_ratio_):
        ax.text(i-0.40, ax.get_ylim()[1] + 0.05, "Explained Variance\n          %.4f"%(ev))

In [98]:
tfidf_word_index = tfidf.get_feature_names()

In [ ]:
start = datetime.now()

svd_variance(svd_5, tfidf_word_index)

end = datetime.now()
print(end - start)

In [ ]:
# Above shows which groups of tweets explained the most on the variance of price increase or decrease
# We should therefore add certain stop-words to the ntlk to run the final regression
# An even better way to identify which words contribute to most variance in data Map out the 
# Eigen vectors to see which tfidf vector makes up SVD component 1, 2, 3..
# Remove words that contribute most to the variance within dimension 2 and 5

In [ ]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
stop += ['http', 'https', 'realdonaldtrump', 'co', 'hilary', 'crooked', 'trump2016', 'make america great'\
        'maga', 'amp']

In [ ]:
sents = pd.read_csv('word_sentiments.csv')

In [ ]:
from collections import defaultdict
sen_dict = defaultdict(dict) # set up a default dictionary with an empty dictionary as default value

In [ ]:
sents.head()

In [ ]:
for row in tqdm_notebook(sents.itertuples()):
    sen_dict[row.pos] [row.word] = {'objectivity': row.objectivity, 'pos_vs_neg': row.pos_vs_neg}

In [ ]:
sp500_trump_df.to_csv('ripe_for_nlp.csv')

In [ ]:
## Turn over to 'Sentiment Analysis' for next stage

In [ ]:
sp500_trump_df_trial = sp500_trump_df[sp500_trump_df.pct_ch_sig==0]

In [ ]:
sp500_trump_df_trial.shape

In [ ]:
X = sp500_trump_df_trial.text
y = sp500_trump_df_trial['pct_ch_sig']
tfidf_trial = TfidfVectorizer(ngram_range=(1,3), stop_words=stop, max_df=10)
X_tfidf_trial = tfidf_trial.fit_transform(X)

In [ ]:
def perform_latent_semantic_analysis(n_components, vectorizer):
    SVD = TruncatedSVD(n_components)
    component_names = ["component_"+str(i+1) for i in range(n_components)] #components being used to categorise tweets & words
    latent_semantic_analysis = pd.DataFrame(SVD.fit_transform(X_tfidf_trial),
                                            index = X,
                                            columns = component_names)
    vocabulary_expression = pd.DataFrame(SVD.components_,
                                         index = component_names,
                                         columns = vectorizer.get_feature_names())
    svd = SVD
    return latent_semantic_analysis, vocabulary_expression, svd

In [ ]:
latent_semantic_analysis, vocabulary_expression, svd = perform_latent_semantic_analysis(10, tfidf_trial)

In [ ]:
latent_semantic_analysis.sort_values('component_9', ascending=False)

In [ ]:
vocabulary_expression.T.sort_values('component_1', ascending=False)

In [ ]:
['interviewed', 'harassment', 'job', 'flotus', 'september11th','neverforget' 'prayers'\
]

In [86]:
import nltk

In [200]:
df_freq = pd.read_csv('freq_trump.csv')

In [168]:
df_ner = pd.read_csv('ner_dataset.csv', encoding = "ISO-8859-1")

In [201]:
df_ner_upper = pd.read_csv('ner_caps.csv')

In [202]:
df_ner_upper.head()

         shape       word    tag
0  capitalized  Thousands      O
1  capitalized     London  B-geo
2  capitalized       Iraq  B-geo
3  capitalized    British  B-gpe
4  capitalized   Families      O

In [208]:
df_freq[df_freq['Unnamed: 0']=='Great Britain']

Empty DataFrame
Columns: [Unnamed: 0, 0]
Index: []

In [197]:
df_new_upper = pd.merge(df_freq, df_ner_upper, left_index=True, right_index=True, how='left')

In [199]:
df_new_upper.head()

  Unnamed: 0     0        shape       word    tag
0      great  1233  capitalized  Thousands      O
1      thank   725  capitalized     London  B-geo
2        amp   659  capitalized       Iraq  B-geo
3      trump   518  capitalized    British  B-gpe
4     people   513  capitalized   Families      O

In [90]:
from nltk.stem import PorterStemmer
stemmer = PorterStemmer()

In [169]:
df_freq.columns = ['word', 'frequency']

In [108]:
df_freq.shape

(132164, 2)

In [187]:
df_freq

                                                    word  frequency
word
great                                              great       1233
thank                                              thank        725
amp                                                  amp        659
trump                                              trump        518
people                                            people        513
...                                                  ...        ...
people became                              people became          1
people became rulers                people became rulers          1
people beginning                        people beginning          1
people beginning understand  people beginning understand          1
level yttidscfft                        level yttidscfft          1

[132164 rows x 2 columns]

In [115]:
df_ner.head()

    Sentence #           Word  POS Tag
0  Sentence: 1      Thousands  NNS   O
1          NaN             of   IN   O
2          NaN  demonstrators  NNS   O
3          NaN           have  VBP   O
4          NaN        marched  VBN   O

In [129]:
df_freq.word[3].lower

In [130]:
lower_words = []
for i in range(0,132164):
    lower_words.append(df_freq.word[i].lower())

In [132]:
lower_ner = []
for i in range(0,1048575):
    lower_ner.append(df_ner.Word[i].lower())

In [170]:
df_freq.word = lower_words
df_ner.Word = lower_ner

In [185]:
df_ner[df_ner.Word=='great']

      Sentence #   Word  POS    Tag
Word
great        NaN  great   JJ      O
great        NaN  great   JJ      O
great        NaN  great   JJ      O
great        NaN  great   JJ      O
great        NaN  great   JJ      O
...          ...    ...  ...    ...
great        NaN  great  NNP  B-geo
great        NaN  great  NNP  I-org
great        NaN  great   JJ      O
great        NaN  great   JJ      O
great        NaN  great   JJ      O

[90 rows x 4 columns]

In [172]:
df_freq.index = df_freq.word
df_ner.index = df_ner.Word

In [177]:
df_new_unstemmed = pd.merge(df_freq, df_ner, left_index=True, right_index=True, how='left')

In [178]:
df_new_unstemmed.drop(columns='Sentence #', inplace=True)

In [179]:
df_new_unstemmed.drop_duplicates(inplace=True)

In [180]:
df_new_unstemmed.sort_values('frequency', ascending = False)

                        word  frequency   Word  POS    Tag
great                  great       1233  great  NNP  B-org
great                  great       1233  great   JJ      O
great                  great       1233  great  NNP  I-geo
great                  great       1233  great  NNP  B-geo
great                  great       1233  great   JJ  B-org
...                      ...        ...    ...  ...    ...
go elsewhere    go elsewhere          1    NaN  NaN    NaN
go dumb one      go dumb one          1    NaN  NaN    NaN
go dumb              go dumb          1    NaN  NaN    NaN
go dqgd4u3uzz  go dqgd4u3uzz          1    NaN  NaN    NaN
۴۰ سال فساد      ۴۰ سال فساد          1    NaN  NaN    NaN

[139193 rows x 5 columns]

In [181]:
df_new_unstemmed.Tag.value_counts()

O        8125
I-org    1152
B-org     877
B-per     574
B-geo     508
I-per     482
B-tim     382
I-geo     378
I-tim     338
B-gpe     140
I-art     124
B-art     101
I-eve      58
B-eve      54
I-gpe      29
B-nat      10
I-nat       6
Name: Tag, dtype: int64

In [140]:
stem_words = []
for i in range(0,132164):
    stem_words.append(stemmer.stem(df_freq.word[i]))

In [138]:
stem_ner = []
for i in range(0,1048575):
    stem_ner.append(stemmer.stem(df_ner.Word[i]))

In [142]:
df_freq.word = stem_words
df_ner.Word = stem_ner

In [189]:
df_ner_upper.head()

         shape       word    tag
0  capitalized  Thousands      O
1  capitalized     London  B-geo
2  capitalized       Iraq  B-geo
3  capitalized    British  B-gpe
4  capitalized   Families      O

In [191]:
df_ner_upper.tag.value_counts()

I-per    2920
B-per    2310
B-geo    2300
O        2299
I-org    2192
B-org    1900
I-geo     770
B-gpe     412
B-tim     205
B-art     162
I-tim     149
I-art     131
B-eve      73
I-eve      60
I-gpe      38
B-nat      18
I-nat      12
Name: tag, dtype: int64

In [184]:
print(df_new_unstemmed.Tag.value_counts())
print(df_new.Tag.value_counts())

O        8125
I-org    1152
B-org     877
B-per     574
B-geo     508
I-per     482
B-tim     382
I-geo     378
I-tim     338
B-gpe     140
I-art     124
B-art     101
I-eve      58
B-eve      54
I-gpe      29
B-nat      10
I-nat       6
Name: Tag, dtype: int64
O        20875
I-org     1971
B-org     1394
B-per      774
I-per      681
B-geo      657
I-geo      583
B-tim      547
I-tim      540
I-art      227
B-gpe      189
B-art      173
I-eve       98
B-eve       82
I-gpe       49
B-nat       20
I-nat       12
Name: Tag, dtype: int64

In [148]:
df_freq.index = df_freq.word
df_ner.index = df_ner.Word

In [149]:
df_new = pd.merge(df_freq, df_ner, left_index=True, right_index=True, how='left')

In [151]:
df_new.sort_values('frequency', ascending = False)

                    word  frequency      Sentence #   Word  POS    Tag
great              great       1233             NaN  great   JJ      O
great              great       1233             NaN  great   JJ      O
great              great       1233             NaN  great   JJ      O
great              great       1233             NaN  great   JJ      O
great              great       1233             NaN  great  NNP  B-org
...                  ...        ...             ...    ...  ...    ...
local              local          1             NaN  local   JJ      O
local              local          1  Sentence: 2158  local   JJ      O
local              local          1             NaN  local   JJ      O
local              local          1             NaN  local   JJ      O
۴۰ سال فساد  ۴۰ سال فساد          1             NaN    NaN  NaN    NaN

[1248498 rows x 6 columns]

In [152]:
df_new.drop_duplicates(inplace=True)

In [155]:
df_new.drop(columns='Sentence #', inplace=True)

In [156]:
df_new.drop_duplicates(inplace=True)

In [158]:
df_new.sort_values('frequency', ascending = False)

                            word  frequency   Word  POS    Tag
great                      great       1233  great   JJ      O
great                      great       1233  great  NNP  B-geo
great                      great       1233  great  NNP  B-org
great                      great       1233  great  NNP  I-geo
great                      great       1233  great  NNP  I-org
...                          ...        ...    ...  ...    ...
got come togeth  got come togeth          1    NaN  NaN    NaN
got com                  got com          1    NaN  NaN    NaN
got china back    got china back          1    NaN  NaN    NaN
got china              got china          1    NaN  NaN    NaN
۴۰ سال فساد          ۴۰ سال فساد          1    NaN  NaN    NaN

[153390 rows x 5 columns]

In [ ]:
def converter(ner_list):
    for item in ner_list:

geo = Geographical Entity

org = Organization

per = Person

gpe = Geopolitical Entity

tim = Time indicator

art = Artifact

eve = Event

nat = Natural Phenomenon

In [164]:
df_new.Tag.value_counts()

O        20875
I-org     1971
B-org     1394
B-per      774
I-per      681
B-geo      657
I-geo      583
B-tim      547
I-tim      540
I-art      227
B-gpe      189
B-art      173
I-eve       98
B-eve       82
I-gpe       49
B-nat       20
I-nat       12
Name: Tag, dtype: int64

In [166]:
df_new[df_new.Tag=='B-per']

              word  frequency      Word  POS    Tag
50              50         26        50  NNP  B-per
abba          abba          2      abba  NNP  B-per
abdul        abdul          1     abdul  NNP  B-per
abdullah  abdullah          1  abdullah  NNP  B-per
abe            abe          9       abe  NNP  B-per
...            ...        ...       ...  ...    ...
xi              xi         23        xi  NNP  B-per
year          year        202      year   NN  B-per
year          year        112      year   NN  B-per
yemen        yemen          1     yemen  NNP  B-per
young        young         17     young  NNP  B-per

[774 rows x 5 columns]

In [276]:
df_final_trump = pd.read_csv('df_final_trump.csv')

In [279]:
df_final_trump = df_final_trump[df_final_trump.text.str.contains(r'tariff', flags=re.IGNORECASE)]

In [281]:
df_final_trump[df_final_trump.pct_ch_sig==0]

,Unnamed: 0,Unnamed: 0.1,index,favorite_count,text,in_reply_to_screen_name,is_retweet,retweet_count,id_str,Symbol,...,price_-1,price_0,vader_compound,vader_neg,vader_neu,vader_pos,pct_ch_sig,tweet_length,pct_ch_sig_-1,pct_ch_sig_-2
4343,4343,2018-04-06 11:11:00+00:00,9818,73956,"Despite the Aluminum Tariffs, Aluminum prices ...",NaN,False,16672,982214297160839173,@ES#,...,0.028433,0.000000,0.2942,0.000,0.897,0.103,0,20,1,0
4551,4551,2018-05-21 11:31:00+00:00,10872,52996,"On China, Barriers and Tariffs to come down fo...",NaN,False,10357,998526637657546753,@ES#,...,0.000000,0.000000,0.0000,0.000,1.000,0.000,0,11,0,0
4800,4800,2018-06-26 11:37:00+00:00,269,54242,....When I had Harley-Davidson officials over ...,NaN,False,11162,1011574256117993472,@ES#,...,0.000000,-0.009196,0.0000,0.000,1.000,0.000,0,20,0,0
4801,4801,2018-06-26 11:49:00+00:00,3592,54873,....We are finishing our study of Tariffs on c...,NaN,False,11242,1011577303023980544,@ES#,...,0.000000,0.009199,0.2500,0.000,0.917,0.083,0,23,0,1
4960,4960,2018-07-24 11:29:00+00:00,1366,87355,Tariffs are the greatest! Either a country whi...,NaN,False,19177,1021719098265362432,@ES#,...,0.000000,0.008873,0.8070,0.000,0.687,0.313,0,20,0,0
4973,4973,2018-07-25 11:01:00+00:00,10239,82434,Every time I see a weak politician asking to s...,NaN,False,19227,1022074252999225344,@ES#,...,0.000000,0.008872,-0.8020,0.313,0.687,0.000,0,24,0,0
5084,5084,2018-08-10 12:47:00+00:00,8792,112838,I have just authorized a doubling of Tariffs o...,NaN,False,33137,1027899286586109955,@ES#,...,0.008797,-0.008796,0.4767,0.000,0.860,0.140,0,22,0,-1
5125,5125,2018-08-15 15:04:00+00:00,11116,76575,"Our Country was built on Tariffs, and Tariffs ...",NaN,False,17926,1029745594540150784,@ES#,...,-0.008908,-0.008908,0.6249,0.000,0.843,0.157,0,24,0,0
5838,5838,2018-11-28 14:43:00+00:00,823,67526,The reason that the small truck business in th...,NaN,False,16012,1067791101782831104,@ES#,...,-0.046369,0.009278,0.4588,0.000,0.885,0.115,0,25,-1,-1
5861,5861,2018-12-03 04:00:00+00:00,10177,134303,China has agreed to reduce and remove tariffs ...,NaN,False,29422,1069441198157455360,@ES#,...,-0.008906,0.008907,0.2732,0.000,0.905,0.095,0,21,0,0
6141,6141,2019-01-28 13:16:00+00:00,982,121081,Tariffs on the “dumping” of Steel in the Unite...,NaN,False,26161,1089874871247687683,@ES#,...,0.000000,0.009437,0.4215,0.000,0.877,0.123,0,21,0,0
6327,6327,2019-03-08 20:45:00+00:00,1753,77856,Aluminum prices are down 12% since I institute...,NaN,False,16534,1104121030862237696,@ES#,...,0.018162,-0.009079,0.2003,0.091,0.788,0.122,0,24,1,0
6735,6735,2019-05-10 12:08:00+00:00,85,101109,Build your products in the United States and t...,NaN,False,22829,1126821318861697024,@ES#,...,0.000000,0.008759,-0.1091,0.201,0.624,0.175,0,12,0,0
6766,6766,2019-05-14 10:15:00+00:00,10466,78976,In one year Tariffs have rebuilt our Steel Ind...,NaN,False,18078,1128242506771128320,@ES#,...,0.000000,-0.008839,0.0000,0.000,1.000,0.000,0,23,0,1
6919,6919,2019-05-30 23:30:00+00:00,1128,159471,"On June 10th, the United States will impose a ...",NaN,False,38241,1134240653926232064,@ES#,...,0.000000,-0.008961,0.1531,0.088,0.800,0.112,0,23,0,0
6920,6920,2019-05-30 23:30:00+00:00,8052,98962,....at which time the Tariffs will be removed....,realDonaldTrump,False,19301,1134240657621438464,@ES#,...,0.000000,-0.008961,0.0000,0.000,1.000,0.000,0,15,0,0
6961,6961,2019-06-05 08:20:00+00:00,6315,70285,“House Republicans support the President on Ta...,NaN,False,16715,1136185948411191297,@ES#,...,-0.008881,0.000000,0.4019,0.000,0.876,0.124,0,20,0,1
7005,7005,2019-06-13 03:50:00+00:00,6090,66161,"“Biden would be China’s Dream Candidate, becau...",NaN,False,16722,1139017233382985728,@ES#,...,0.008680,-0.008679,-0.5574,0.258,0.664,0.078,0,21,0,0
7203,7203,2019-07-09 12:44:00+00:00,570,92663,India has long had a field day putting Tariffs...,NaN,False,19742,1148573632869875712,@ES#,...,-0.050531,-0.008426,0.1007,0.131,0.715,0.154,0,15,-1,0
7280,7280,2019-07-15 10:43:00+00:00,9722,108690,China’s 2nd Quarter growth is the slowest it h...,NaN,False,20708,1150717474624692224,@ES#,...,0.008280,0.008280,0.6597,0.000,0.795,0.205,0,23,0,0
7363,7363,2019-07-23 12:23:00+00:00,2662,88193,"....Tariffs, Remittance Fees, or all of the ab...",realDonaldTrump,False,15890,1153641907781873664,@ES#,...,0.000000,-0.008334,-0.3412,0.112,0.888,0.000,0,20,0,0
7423,7423,2019-07-26 15:25:00+00:00,10516,107847,"Apple will not be given Tariff waiver, or reli...",NaN,False,23475,1154774656861257732,@ES#,...,0.000000,0.008277,0.2942,0.077,0.804,0.119,0,25,0,0
7456,7456,2019-07-30 12:40:00+00:00,8940,60918,China has lost 5 million jobs and two million ...,NaN,False,14554,1156182666871549952,@ES#,...,-0.008311,0.000000,-0.3182,0.103,0.897,0.000,0,22,0,0
7492,7492,2019-08-01 17:26:00+00:00,791,70558,"...during the talks the U.S. will start, on Se...",realDonaldTrump,False,14697,1156979446877962243,@ES#,...,0.016614,0.000000,0.0000,0.000,1.000,0.000,0,21,1,0

In [222]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
stop += ['http', 'https', 'realdonaldtrump', 'co', 'The']

In [223]:
cvec = CountVectorizer(strip_accents='unicode', ngram_range=(1, 3), lowercase=False, stop_words=stop)
X_all = cvec.fit_transform(df_final_trump.text)

In [224]:
cv_df = pd.DataFrame(X_all.toarray(), columns=cvec.get_feature_names())
freq_upper = pd.DataFrame(cv_df.sum().sort_values(ascending=False))

In [225]:
freq_upper.head()

          0
great   678
amp     659
Thank   571
Trump   479
people  442

In [228]:
df_ner_upper.index = df_ner_upper.word

In [229]:
df_new_upper = pd.merge(freq_upper, df_ner_upper, left_index=True, right_index=True, how='left')

In [235]:
df_new_upper.sort_values(0, ascending=False)

                                        0 shape word  tag
great                                 678   NaN  NaN  NaN
amp                                   659   NaN  NaN  NaN
Thank                                 571   NaN  NaN  NaN
Trump                                 479   NaN  NaN  NaN
people                                442   NaN  NaN  NaN
...                                   ...   ...  ...  ...
Securi                                  1   NaN  NaN  NaN
Secur it4P8oQShG                        1   NaN  NaN  NaN
Secur                                   1   NaN  NaN  NaN
SecretaryZinke SecPriceMD Yxm94XKtuv    1   NaN  NaN  NaN
۴۰ سال فساد                             1   NaN  NaN  NaN

[148158 rows x 4 columns]